services:
  app:
    build:
      context: .
    container_name: pokefind-frontend
    restart: unless-stopped
    networks:
      - proxy
      - internal

networks:
  proxy:
    external: true
  internal:
    driver: bridge
