services:
  frontend:
    build:
      context: ./frontend
    container_name: pokefind-frontend
    restart: unless-stopped
    depends_on:
      - api
    networks:
      - proxy
      - internal

  api:
    build:
      context: ./backend
    container_name: pokefind-api
    restart: unless-stopped
    environment:
      PORT: "3001"
    networks:
      - internal

networks:
  proxy:
    external: true
  internal:
    driver: bridge
